Repository nomiddlename/date-format, pull requests merged in 2022-06, with the labels that each got.

#69 test: use `new Date(0)` instead of `new Date()` before setting every field
  test/parse-test.js
Labels: tests

#70 chore(deps): updated dependencies
  package-lock.json
  package.json
Labels: dependencies

#71 docs: updated changelog for 4.0.11
  CHANGELOG.md
Labels: documentation

#72 docs: renamed myself in changelog
  CHANGELOG.md
Labels: documentation
